stages:
  - build
  - test
  - deploy

variables:
  MAVEN_CLI_OPTS: "-s settings.xml --batch-mode --errors --fail-at-end --show-version --update-snapshots"

build:
  stage: build
  image: maven:3.8.6-openjdk-17
  script:
    - echo "Building the application..."
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

test:
  stage: test
  image: maven:3.8.6-openjdk-17
  script:
    - echo "Running tests..."
    - mvn $MAVEN_CLI_OPTS test

deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh-client
  script:
    - echo "Deploying to the VM..."
